In [6]:
import tensorflow as tf
import numpy as np

In [5]:
#anything flowing inside the tensorflow framework is tensor

t1 = tf.Variable([1,2,3]) # work as parameter which can be upated
t2 = tf.constant([1,2,3]) # dataset : constant tensor

print(t1)
print(t2,"\n")
print(type(t1)) #ResourceVariable -> mutable
print(type(t2)) #EagerTensor -> immutable



<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
tf.Tensor([1 2 3], shape=(3,), dtype=int32) 

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [10]:
# change python list and numpy array to tensorflow tensor

test_list = [1,2,3]
test_np = np.array([1,2,3])

print(type(test_list))
print(type(test_np),"\n")

#----------------------------
#tf.constant
lst_constant = tf.constant(test_list)
np_constant = tf.constant(test_np)

print(lst_constant) #EagerTensor
print(np_constant,"\n") #EagerTensor

print(type(lst_constant))
print(type(np_constant),"\n")

#----------------------------
#tf.Variable
lst_val = tf.Variable(test_list)
np_val = tf.Variable(test_np)

print(lst_val) #ResourceVariable
print(np_val,"\n") #ResourceVariable

print(type(lst_val))
print(type(np_val),"\n")


<class 'list'>
<class 'numpy.ndarray'> 

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int64) 

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'> 

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([1, 2, 3])> 

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'> 



In [15]:
# constant tensor -(casting)-> variable tensor
t_constant = tf.constant(test_list)
t_Variable = tf.Variable(test_list)

t1 = tf.constant(t_Variable)
t2 = tf.Variable(t_constant)

print(type(t1))
print(type(t2))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [17]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

t1 = tf.Variable(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1+t2
print(type(t3))

t1 = tf.constant(test_list1)
t2 = tf.constant(test_list2)

t3 = t1+t2
print(type(t3))

t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1+t2
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
