In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt

## How to creat train & validation data set

In [28]:
entire_ds_x = np.arange(10).reshape(-1,1)
entire_ds_y = 3*entire_ds_x+1

train_validation_ds = tf.data.Dataset.from_tensor_slices((entire_ds_x,entire_ds_y))

n_train_validation = len(train_validation_ds)
train_ratio = 0.8
#get num of training example
n_train = int(n_train_validation*train_ratio)
n_validation = n_train_validation - n_train

#training ds take first n_train examples
train_ds = train_validation_df.take(n_train)

#skip the first n_train example
remaining_ds = train_validation_df.skip(n_train)

#take n_validation example 
valid_ds = remaining_ds.take(n_validation)


In [33]:
for i,(x,y) in enumerate(train_ds):
    print(i)
    print(x,"\n",y,"\n")

0
tf.Tensor([0], shape=(1,), dtype=int64) 
 tf.Tensor([1], shape=(1,), dtype=int64) 

1
tf.Tensor([1], shape=(1,), dtype=int64) 
 tf.Tensor([4], shape=(1,), dtype=int64) 

2
tf.Tensor([2], shape=(1,), dtype=int64) 
 tf.Tensor([7], shape=(1,), dtype=int64) 

3
tf.Tensor([3], shape=(1,), dtype=int64) 
 tf.Tensor([10], shape=(1,), dtype=int64) 

4
tf.Tensor([4], shape=(1,), dtype=int64) 
 tf.Tensor([13], shape=(1,), dtype=int64) 

5
tf.Tensor([5], shape=(1,), dtype=int64) 
 tf.Tensor([16], shape=(1,), dtype=int64) 

6
tf.Tensor([6], shape=(1,), dtype=int64) 
 tf.Tensor([19], shape=(1,), dtype=int64) 

7
tf.Tensor([7], shape=(1,), dtype=int64) 
 tf.Tensor([22], shape=(1,), dtype=int64) 



In [32]:
for i,(x,y) in enumerate(valid_ds):
    print(i)
    print(x,"\n",y,"\n")

0
tf.Tensor([8], shape=(1,), dtype=int64) 
 tf.Tensor([25], shape=(1,), dtype=int64) 

1
tf.Tensor([9], shape=(1,), dtype=int64) 
 tf.Tensor([28], shape=(1,), dtype=int64) 



## Practice using MNIST

In [51]:
#ds_info is needed to get the shape of the entire dataset
# as_supervised: return X,y in tuple form 

(train_validation_ds,test_ds),ds_info = tfds.load(name = "mnist", 
                                                  shuffle_files = True, 
                                                  as_supervised = True, 
                                                  split = ["train", "test"], 
                                                  with_info = True)

In [52]:
n_train_validation =  ds_info.splits["train"].num_examples #60000
train_ratio = 0.8
n_train = int(n_train_validation*train_ratio)
n_validation = n_train_validation - n_train

train_ds = train_validation_ds.take(n_train)
validation_ds = train_validation_ds.skip(n_train).take(n_validation)

train_ds = train_ds.shuffle(100).batch(32)
validation_ds = validation_ds.batch(32)
test_ds = test_ds

In [53]:
print(len(train_ds)) #1500*32
print(len(validation_ds)) #375*32
print(len(test_ds))

1500
375
10000
