In [1]:
import tensorflow as tf
import numpy as np

In [7]:
t1 = tf.constant([1,2,3])
t2 = tf.constant([10,20,30])

#basic python list: concate
py_lst1 = [1,2,3]
py_lst2 = [10,20,30]
print(py_lst1+py_lst2)
print()

#element-wise addition
print(t1-t2)
print()
#element-wise 
print(t1/t2)
print()
#element-wise 
print(t1*t2)
print()
#element-wise 
print(t1//t2)
print()
#element-wise 
print(t1%t2)
print()

[1, 2, 3, 10, 20, 30]

tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)

tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)

tf.Tensor([10 40 90], shape=(3,), dtype=int32)

tf.Tensor([0 0 0], shape=(3,), dtype=int32)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)



In [14]:
t1 = tf.random.normal(shape= (3,4), mean = 0, stddev=5)
t2 = tf.random.normal(shape= (3,4), mean = 0, stddev=5)

t1 = tf.cast(t1, dtype= tf.int16)
t2 = tf.cast(t2, dtype= tf.int16)

print(t1.numpy(),"\n")
print(t2.numpy())
print("\n", (t1+t2).numpy())

[[ 0  0 -1  0]
 [ 1 -3 -5 -2]
 [ 0 -6  2  7]] 

[[ 5 -4  0  5]
 [-1  0  0 -3]
 [-1 -5  0  5]]

 [[  5  -4  -1   5]
 [  0  -3  -5  -5]
 [ -1 -11   2  12]]


In [20]:
# broadcasting
t1 = tf.random.normal(shape= (3,4), mean = 0, stddev=5)
t2 = tf.random.normal(shape= (1,4), mean = 0, stddev=5)

t1 = tf.cast(t1, dtype= tf.int16)
t2 = tf.cast(t2, dtype= tf.int16)

print(t1.numpy(),"\n")
print(t2.numpy())
print("\n", (t1+t2).numpy())
print()

# broadcasting
t1 = tf.random.normal(shape= (3,4), mean = 0, stddev=5)
t2 = tf.random.normal(shape= (1,1), mean = 0, stddev=5)

t1 = tf.cast(t1, dtype= tf.int16)
t2 = tf.cast(t2, dtype= tf.int16)

print(t1.numpy(),"\n")
print(t2.numpy())
print("\n", (t1+t2).numpy())

print()

# broadcasting
t1 = tf.random.normal(shape= (3,4), mean = 0, stddev=5)
t2 = tf.random.normal(shape= (3,1), mean = 0, stddev=5)

t1 = tf.cast(t1, dtype= tf.int16)
t2 = tf.cast(t2, dtype= tf.int16)

print(t1.numpy(),"\n")
print(t2.numpy())
print("\n", (t1+t2).numpy())
print()
# broadcasting
t1 = tf.random.normal(shape= (3,1), mean = 0, stddev=5)
t2 = tf.random.normal(shape= (1,4), mean = 0, stddev=5)

t1 = tf.cast(t1, dtype= tf.int16)
t2 = tf.cast(t2, dtype= tf.int16)

print(t1.numpy(),"\n")
print(t2.numpy())
print("\n", (t1+t2).numpy())

[[ -5  -7  -3  -3]
 [-10   5  -9   8]
 [  0  -6   7  -6]] 

[[ 5  0  5 -9]]

 [[  0  -7   2 -12]
 [ -5   5  -4  -1]
 [  5  -6  12 -15]]

[[  2  -4  -6 -10]
 [  0  -4  -1   3]
 [  8   0   2  -6]] 

[[-4]]

 [[ -2  -8 -10 -14]
 [ -4  -8  -5  -1]
 [  4  -4  -2 -10]]

[[ -1   1  -1   2]
 [  5  -2   0   3]
 [-11   1   0   0]] 

[[ 1]
 [ 0]
 [-3]]

 [[  0   2   0   3]
 [  5  -2   0   3]
 [-14  -2  -3  -3]]

[[ 0]
 [-1]
 [-2]] 

[[2 3 1 2]]

 [[ 2  3  1  2]
 [ 1  2  0  1]
 [ 0  1 -1  0]]


In [31]:
#column: attribute, row: single instance

# tf.reduce_prod
# tf.reduce_max
# tf.reduce_min

# tf.reduce_mean
# tf.reduce_std
# tf.reduce_variance

# tf.reduce_all
# tf.reduce_any

t1 = tf.random.normal(shape= (7,3), mean = 0, stddev=5)
t1 = tf.cast(t1, dtype = tf.int16)
print(t1.numpy())

# row sum, column sum
#reduced sum, reduce prod

print(tf.reduce_sum(t1).numpy()) # all element sum
print(tf.reduce_sum(t1, axis= 0).numpy()) 
print(tf.reduce_sum(t1, axis= 1).numpy()) 

[[ 3  1 -4]
 [-6  4 11]
 [-3  3  0]
 [ 1  2 -7]
 [ 0  4  5]
 [ 2  3  4]
 [-7  8  0]]
24
[-10  25   9]
[ 0  9  0 -4  9  9  1]


In [36]:
#image 
t1 = tf.random.normal(shape= (128,128,3), mean = 0, stddev=5)
t1 = tf.cast(t1, dtype = tf.int16)
print(t1.numpy().shape)

#In RGB channel, get sum of the pixel values at same location
res = tf.reduce_sum(t1, axis =2)
print(res.shape)

(128, 128, 3)
(128, 128)


In [37]:
#image 
t1 = tf.random.normal(shape= (128,128,3), mean = 0, stddev=5)
t1 = tf.cast(t1, dtype = tf.int16)
print(t1.numpy().shape)

#In RGB channel, get average of the pixel values at same location
res = tf.reduce_mean(t1, axis =2)
print(res.shape)

(128, 128, 3)
(128, 128)
